-- Main Shipment Data Query (from shipments_sql_agent.py)
-- This is the core query used to fetch comprehensive shipment data for a customer

WITH
/* 1) Anchor to the customer's orders (left-join base) */
orders_base AS (
  SELECT
      O.ORDER_ID,
      O.ORDER_KEY,
      O.CUSTOMER_ID,
      O.ORDER_PLACED_DTTM,
      O.ORDER_STATUS,
      O.ORDER_CHANNEL_MIX,
      O.ORDER_PACKAGE_COUNT,
      O.ORDER_CANCEL_DTTM,
      O.ORDER_STATUS_DESCRIPTION,
      O.ORDER_AUTO_REORDER_FLAG
  FROM EDLDB.CHEWYBI.ORDERS AS O
  WHERE O.CUSTOMER_ID = :customer_id
  AND O.ORDER_PLACED_DTTM >= current_date - interval '90 days'
),

/* 2) Aggregate active pet details once per customer (flat strings; no nesting) */
active_pets AS (
  SELECT
      PPA.CUSTOMER_ID,
      COUNT(*) AS PETS_ACTIVE_COUNT,
      LISTAGG(PPA.PET_NAME, ' | ') WITHIN GROUP (ORDER BY PPA.PET_NAME) AS PETS_ACTIVE_NAMES,
      LISTAGG(PPA.PET_TYPE, ' | ') WITHIN GROUP (ORDER BY PPA.PET_TYPE) AS PETS_ACTIVE_TYPES,
      LISTAGG( PPA.PET_AGE, ' | ') WITHIN GROUP (ORDER BY PPA.PET_AGE) AS PETS_ACTIVE_AGE,
      LISTAGG( PPA.WEIGHT, ' | ') WITHIN GROUP (ORDER BY PPA.WEIGHT) AS PETS_ACTIVE_WEIGHT,
      LISTAGG( PPA.PET_BREED, ' | ') WITHIN GROUP (ORDER BY PPA.PET_BREED) AS PETS_ACTIVE_BREED,
      LISTAGG( PPA.LIFESTAGE, ' | ') WITHIN GROUP (ORDER BY PPA.LIFESTAGE) AS PETS_ACTIVE_LIFESTAGE,
      LISTAGG( PPA.GENDER, ' | ') WITHIN GROUP (ORDER BY PPA.GENDER) AS PETS_ACTIVE_GENDER,
      LISTAGG( PPA.MEDICATION, ' | ') WITHIN GROUP (ORDER BY PPA.MEDICATION) AS PETS_ACTIVE_MEDICATION
  FROM EDLDB.CHEWYBI.PET_PROFILE_AGGREGATE AS PPA
  WHERE PPA.CUSTOMER_ID = :customer_id
    AND PPA.PP_STATUS ilike 'Active'
  GROUP BY PPA.CUSTOMER_ID
)
, rx_approval_metrics AS (
  SELECT RXV.ORDER_ID,
  RXV.ORDER_LINE_ID,
  RXV.AUTOSHIP AS RX_AUTOSHIP,
  RXV.TIME_SENSITIVE,
  RXV.APPROVAL_CHANNEL,
  RXV.ORDER_ITEM_BLOCK_REASON,
  RXV.STATE_CHANGE_REASON,
  RXV.MIN_PENDING_DATETIME,
  RXV.MAX_PENDING_DATETIME,
  RXV.MIN_CANCELED_DATETIME,
  RXV.MAX_CANCELED_DATETIME,
  RXV.MIN_APPROVED_DATETIME,
  RXV.MAX_APPROVED_DATETIME,
  RXV.MIN_VALIDATED_DATETIME,
  RXV.MAX_VALIDATED_DATETIME,
  RXV.MIN_DENIED_DATETIME,
  RXV.MAX_DENIED_DATETIME,
  RXV.MIN_APPROVED_DENIED_DATETIME,
  RXV.MAX_APPROVED_DENIED_DATETIME,
  RXV.MIN_PRESCRIPTION_APPROVED_DATETIME,
  RXV.MAX_PRESCRIPTION_APPROVED_DATETIME
  FROM EDLDB.CHEWYBI.RX_APPROVAL_METRICS RXV
  WHERE RXV.ORDER_ID IN (SELECT ORDER_ID FROM orders_base)
),

/* 3) Line items rolled up per shipment to avoid shipment duplication */
line_items_by_shipment AS (
  SELECT
      OLCM.ORDER_ORDER_ID,
      OLCM.SHIPMENT_TRACKING_NUMBER,
      COUNT(DISTINCT OLCM.PRODUCT_KEY)                           AS LI_PRODUCT_COUNT,
      LISTAGG(DISTINCT P.PRODUCT_PART_NUMBER::STRING, ' | ')
        WITHIN GROUP (ORDER BY 1)                     AS LI_PRODUCT_PART_NUMBERS,
      LISTAGG(DISTINCT P.PRODUCT_NAME, ' | ')
        WITHIN GROUP (ORDER BY P.PRODUCT_NAME)                   AS LI_PRODUCT_NAMES,
      LISTAGG(DISTINCT P.PRODUCT_MERCH_CLASSIFICATION1, ' | ')
        WITHIN GROUP (ORDER BY P.PRODUCT_MERCH_CLASSIFICATION1)                   AS LI_MC1S,
      LISTAGG(DISTINCT P.PRODUCT_MERCH_CLASSIFICATION2, ' | ')
        WITHIN GROUP (ORDER BY P.PRODUCT_MERCH_CLASSIFICATION2)                   AS LI_MC2S,
      LISTAGG(DISTINCT P.PRODUCT_MERCH_CLASSIFICATION3, ' | ')
        WITHIN GROUP (ORDER BY P.PRODUCT_MERCH_CLASSIFICATION3)                   AS LI_MC3S,     
      LISTAGG(DISTINCT P.PRODUCT_CATEGORY_LEVEL1, ' | ')
        WITHIN GROUP (ORDER BY P.PRODUCT_CATEGORY_LEVEL1)        AS LI_PRODUCT_CAT_L1,
      LISTAGG(DISTINCT P.PRODUCT_CATEGORY_LEVEL2, ' | ')
        WITHIN GROUP (ORDER BY P.PRODUCT_CATEGORY_LEVEL2)        AS LI_PRODUCT_CAT_L2,
      LISTAGG(DISTINCT P.PRODUCT_CATEGORY_LEVEL3, ' | ')
        WITHIN GROUP (ORDER BY P.PRODUCT_CATEGORY_LEVEL3)        AS LI_PRODUCT_CAT_L3
  FROM EDLDB.CHEWYBI.ORDER_LINE_COST_MEASURES AS OLCM
  JOIN orders_base AS OB
    ON OLCM.ORDER_KEY = OB.ORDER_KEY
  LEFT JOIN EDLDB.CHEWYBI.PRODUCTS AS P
    ON OLCM.PRODUCT_KEY = P.PRODUCT_KEY
  GROUP BY OLCM.ORDER_ORDER_ID,OLCM.SHIPMENT_TRACKING_NUMBER
),

/* 4) Customers (selected fields only) */
cust AS (
  SELECT
      C.CUSTOMER_ID
      ,C.CUSTOMER_REGISTRATION_DTTM
      ,C.CUSTOMER_LAST_SESSION_DTTM
      ,C.CUSTOMER_ORDER_FIRST_AUTOREORDER_PLACED_DTTM
      ,C.CUSTOMER_PREFERRED_FOOD_BRANDS
      ,C.CUSTOMER_PETS
      ,C.CUSTOMER_AUTOSHIP_TOTAL_COUNT
      ,C.CUSTOMER_AUTOSHIP_CANCELED_COUNT
      ,C.CUSTOMER_AUTOSHIP_ACTIVE_COUNT
      ,C.CUSTOMER_AUTOSHIP_ACTIVE_FLAG
      ,C.CUSTOMER_AUTOSHIP_NEXT_DTTM
      ,C.CUSTOMER_AUTOSHIP_LAST_CANCEL_DTTM
      ,C.CUSTOMER_AUTOSHIP_LAST_CREATE_DTTM
  FROM EDLDB.CHEWYBI.CUSTOMERS AS C
  WHERE C.CUSTOMER_ID = :customer_id
)

/* 5) Final select — one row per shipment (tracking number) */
SELECT
    /* All columns from SHIPMENT_TRANSACTIONS as required */
    ST.*,

    /* Prefixed & useful columns from ORDERS */
    OB.ORDER_ID                        AS ORDERS_ORDER_ID,
    OB.ORDER_KEY                       AS ORDERS_ORDER_KEY,
    OB.CUSTOMER_ID                     AS ORDERS_CUSTOMER_ID,
    OB.ORDER_PLACED_DTTM               AS ORDERS_ORDER_PLACED_DTTM,
    OB.ORDER_AUTO_REORDER_FLAG         AS ORDERS_ORDER_AUTO_REORDER_FLAG,
    OB.ORDER_STATUS                    AS ORDERS_ORDER_STATUS,
    OB.ORDER_CHANNEL_MIX               AS ORDERS_ORDER_CHANNEL_MIX,
    OB.ORDER_PACKAGE_COUNT             AS ORDERS_ORDER_PACKAGE_COUNT,

    /* Shipment KPIs / derived fields */
    DATEDIFF('day', OB.ORDER_PLACED_DTTM, ST.BULK_TRACK_DELIVERY_DTTM) AS CLICK_TO_DELIVER_DAYS,
    DATEDIFF('day', OB.ORDER_PLACED_DTTM, ST.RELEASE_DTTM) AS CLICK_TO_RELEASE_DAYS,
    DATEDIFF('day', ST.RELEASE_DTTM, ST.SHIPMENT_SHIPPED_DTTM) AS RELEASE_TO_SHIP_DAYS,
    DATEDIFF('day', ST.SHIPMENT_SHIPPED_DTTM, ST.BULK_TRACK_DELIVERY_DTTM) AS SHIP_TO_DELIVER_DAYS,
    ST.BULK_TRACK_LB_PACKAGE_WEIGHT                                     AS PACKAGE_WEIGHT_LB,
    ST.FFMCENTER_NAME                                                   AS FULFILLMENT_CENTER_NAME,

    /* Wizmo (selected, shipment-level) */
    WZ.CHEWY_PROMISED_DELIVERY_DATE        AS WIZMO_PROMISED_DELIVERY_DATE,
    WZ.CURRENT_CHEWY_ARRIVAL_DATE          AS WIZMO_CURRENT_ARRIVAL_DATE,
    WZ.CHEWY_CURRENT_PKG_STATUS            AS WIZMO_CURRENT_PKG_STATUS,
    WZ.SHIPMENT_WAS_LOST                   AS WIZMO_SHIPMENT_WAS_LOST,
    WZ.SHIPMENT_WAS_DELAYED                AS WIZMO_SHIPMENT_WAS_DELAYED,

    /* Customer (selected, prefixed) */
    CUST.*,

    /* Pets (aggregated) */
    AP.PETS_ACTIVE_COUNT                   AS PETS_ACTIVE_COUNT,
    AP.PETS_ACTIVE_NAMES                   AS PETS_ACTIVE_NAMES,
    AP.PETS_ACTIVE_TYPES                   AS PETS_ACTIVE_TYPES,
    AP.PETS_ACTIVE_AGE                     AS PETS_ACTIVE_AGE,
    AP.PETS_ACTIVE_BREED                   AS PETS_ACTIVE_BREED,
    AP.PETS_ACTIVE_WEIGHT                  AS PETS_ACTIVE_WEIGHT,
    AP.PETS_ACTIVE_LIFESTAGE               AS PETS_ACTIVE_LIFESTAGE,
    AP.PETS_ACTIVE_GENDER                  AS PETS_ACTIVE_GENDER,
    AP.PETS_ACTIVE_MEDICATION              AS PETS_ACTIVE_MEDICATION,

    /* Line items (aggregated per shipment) */
    LI.LI_PRODUCT_COUNT                    AS LINEITEM_PRODUCT_COUNT,
    LI.LI_PRODUCT_PART_NUMBERS             AS LINEITEM_PRODUCT_PART_NUMBERS,
    LI.LI_PRODUCT_NAMES                    AS LINEITEM_PRODUCT_NAMES,
    LI.LI_MC1S                             AS LINEITEM_PRODUCT_MC1,
    LI.LI_MC2S                             AS LINEITEM_PRODUCT_MC2,
    LI.LI_MC3S                             AS LINEITEM_PRODUCT_MC3,
    LI.LI_PRODUCT_CAT_L1                   AS LINEITEM_PRODUCT_CAT_L1,
    LI.LI_PRODUCT_CAT_L2                   AS LINEITEM_PRODUCT_CAT_L2,
    LI.LI_PRODUCT_CAT_L3                   AS LINEITEM_PRODUCT_CAT_L3,
    RXA.*

FROM orders_base AS OB
LEFT JOIN EDLDB.CHEWYBI.SHIPMENT_TRANSACTIONS AS ST
  ON OB.ORDER_ID = ST.ORDER_ID
LEFT JOIN EDLDB.CHEWYBI.SHIPMENT_WIZMO AS WZ
  ON ST.ORDER_ID = WZ.ORDER_ID
 AND ST.SHIPMENT_TRACKING_NUMBER = WZ.SHIPMENT_TRACKING_NUMBER
LEFT JOIN cust AS CUST
  ON OB.CUSTOMER_ID = CUST.CUSTOMER_ID
LEFT JOIN active_pets AS AP
  ON OB.CUSTOMER_ID = AP.CUSTOMER_ID
LEFT JOIN line_items_by_shipment AS LI
  ON (ST.SHIPMENT_TRACKING_NUMBER = LI.SHIPMENT_TRACKING_NUMBER or LI.SHIPMENT_TRACKING_NUMBER is null)
  AND ST.ORDER_ID = LI.ORDER_ORDER_ID
LEFT JOIN rx_approval_metrics RXA
  ON OB.ORDER_ID = RXA.ORDER_ID

-- Only actual shipments (unique tracking numbers). If you want orders without shipments, remove this filter.
WHERE ST.SHIPMENT_TRACKING_NUMBER IS NOT NULL

-- De-dupe in case upstream data has repeated scans/updates per tracking #
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY ST.SHIPMENT_TRACKING_NUMBER
  ORDER BY COALESCE(ST.DW_UPDATE_DTTM, ST.SHIPMENT_SHIPPED_DTTM, OB.ORDER_PLACED_DTTM) DESC
) = 1

-- Sort by delivered date asc, fallback to order placed
ORDER BY
  ST.BULK_TRACK_DELIVERY_DTTM DESC NULLS LAST,
  OB.ORDER_PLACED_DTTM DESC;
