WITH base AS (
    SELECT ORDER_ID, ORDER_PLACED_DTTM,
        COUNT(DISTINCT PRODUCT_KEY) AS LI_PRODUCT_COUNT,
        LISTAGG(PRODUCT_PART_NUMBER, ' | ') WITHIN GROUP (ORDER BY 1) AS LI_PRODUCT_PART_NUMBERS,
        LISTAGG(PRODUCT_NAME, ' | ') WITHIN GROUP (ORDER BY PRODUCT_NAME) AS LI_PRODUCT_NAMES,
        LISTAGG(PRODUCT_MERCH_CLASSIFICATION1, ' | ') WITHIN GROUP (ORDER BY PRODUCT_MERCH_CLASSIFICATION1) AS LI_MC1S,
        LISTAGG(PRODUCT_MERCH_CLASSIFICATION2, ' | ') WITHIN GROUP (ORDER BY PRODUCT_MERCH_CLASSIFICATION2) AS LI_MC2S,
        LISTAGG(PRODUCT_MERCH_CLASSIFICATION3, ' | ') WITHIN GROUP (ORDER BY PRODUCT_MERCH_CLASSIFICATION3) AS LI_MC3S,
        LISTAGG(PRODUCT_CATEGORY_LEVEL1, ' | ') WITHIN GROUP (ORDER BY PRODUCT_CATEGORY_LEVEL1) AS LI_PRODUCT_CAT_L1,
        LISTAGG(PRODUCT_CATEGORY_LEVEL2, ' | ') WITHIN GROUP (ORDER BY PRODUCT_CATEGORY_LEVEL2) AS LI_PRODUCT_CAT_L2,
        LISTAGG(PRODUCT_CATEGORY_LEVEL3, ' | ') WITHIN GROUP (ORDER BY PRODUCT_CATEGORY_LEVEL3) AS LI_PRODUCT_CAT_L3
    FROM edldb.chewybi.orders
    JOIN edldb.chewybi.order_line_cost_measures USING (order_key)
    JOIN edldb.chewybi.products USING (product_key)
    WHERE customer_id = :customer_id
    AND ORDER_PLACED_DTTM >= current_date - interval '90 days'
    GROUP BY ALL
),
sessions as (
select LEG_ID, SESSION_ID, INCIDENT_ID
FROM EDLDB.CS_SANDBOX.CONTACT_TRANSCRIPTS
WHERE CUSTOMER_ID = :customer_id

GROUP BY ALL
UNION
select LEG_ID, SESSION_ID, INCIDENT_ID
FROM EDLDB.CS_SANDBOX.CONTACTS_BRD
WHERE CUSTOMER_ID = :customer_id

GROUP BY ALL
)
,transcripts AS (
    SELECT LEG_ID, SESSION_ID, INCIDENT_ID, SESSION_CHANNEL, CUSTOMER_ID, 
           EMPLOYEE_ID, EMPLOYEE_USER_NAME, SESSION_START_DTTM, LEG_START_DTTM, 
           LEG_END_DTTM, SESSION_END_DTTM, LEG_TYPE, LEG_SEQUENCE_NUMBER, 
           SUBJECT, TRANSCRIPT, SESSION_INITIAL_DIRECTION, LOAD_DTTM
    FROM EDLDB.CS_SANDBOX.CONTACT_TRANSCRIPTS
    WHERE CUSTOMER_ID = :customer_id
    ORDER BY SESSION_START_DTTM DESC
),
incident_surveys AS (
    SELECT DISTINCT INCIDENT_ID, CUSTOMER_ID, SURVEY_OVERALL_SATISFACTION, SURVEY_RESOLVED, EASY_TO_RESOLVE_ISSUE, CSAT_COMMENTS, ENGAGE_RECORDED_DATE
    FROM EDLDB.CS_SANDBOX.VW_CSAT_SURVEY_INCIDENTS
    WHERE TRUE
    AND CUSTOMER_ID = :customer_id
    AND CSAT_COMMENTS IS NOT NULL
    AND CSAT_COMMENTS != ''
)
SELECT s.LEG_ID, s.SESSION_ID, s.INCIDENT_ID, c.CUSTOMER_ID, TRANSCRIPT, coalesce(c.SESSION_START_DTTM,tr.SESSION_START_DTTM) as SESSION_START_DTTM, 
       coalesce(c.LEG_START_DTTM,tr.LEG_START_DTTM) as LEG_START_DTTM, coalesce(c.SESSION_END_DTTM,tr.SESSION_END_DTTM) as SESSION_END_DTTM,
       coalesce(c.SESSION_CHANNEL,tr.SESSION_CHANNEL) as SESSION_CHANNEL, c.SESSION_INGRESS_POINT, 
       c.SESSION_INITIAL_DIRECTION, coalesce(c.LEG_TYPE, tr.LEG_TYPE) as LEG_TYPE, HANDLE_TIME_SEC, ORDER_ID,
       LI_PRODUCT_PART_NUMBERS, LI_PRODUCT_NAMES, LI_MC1S, LI_MC2S, LI_MC3S, LI_PRODUCT_CAT_L1, LI_PRODUCT_CAT_L2, LI_PRODUCT_CAT_L3,
       SESSION_RATING, c.EMPLOYEE_ID, EMPLOYEE_FULL_NAME, CATEGORY_LEVEL_1, 
       CATEGORY_LEVEL_2, CATEGORY_LEVEL_3, CATEGORY_LEVEL_4, 
       isv.SURVEY_OVERALL_SATISFACTION, isv.SURVEY_RESOLVED, isv.EASY_TO_RESOLVE_ISSUE, isv.CSAT_COMMENTS
FROM sessions s
LEFT JOIN EDLDB.CS_SANDBOX.CONTACTS_BRD c ON s.INCIDENT_ID = c.INCIDENT_ID AND s.LEG_ID = c.LEG_ID AND s.SESSION_ID = c.SESSION_ID
LEFT JOIN incident_surveys isv ON s.INCIDENT_ID = isv.INCIDENT_ID
LEFT JOIN base b USING (ORDER_ID)
LEFT JOIN transcripts tr
ON tr.LEG_ID = s.LEG_ID
AND tr.SESSION_ID = s.SESSION_ID
AND (tr.INCIDENT_ID = s.INCIDENT_ID OR tr.INCIDENT_ID IS NULL)
ORDER BY SESSION_START_DTTM DESC;
