-- Customer ZIP Code Performance Analysis (from tool_calls.py)
-- Analyzes customer-specific shipping performance by ZIP code

WITH BASE AS (
    SELECT 
        POSTCODE, 
        SHIPMENT_TRACKING_NUMBER, 
        BULK_TRACK_LB_PACKAGE_WEIGHT AS PACKAGE_WEIGHT, 
        SHIPMENT_SHIP_ROUTE, 
        DATEDIFF('DAY', ORDER_PLACED_DTTM, BULK_TRACK_DELIVERY_DTTM) AS CTD,
        DATEDIFF('day', ORDER_PLACED_DTTM, RELEASE_DTTM) AS CTR,
        DATEDIFF('day', RELEASE_DTTM, SHIPMENT_SHIPPED_DTTM) AS RTS,
        DATEDIFF('day', SHIPMENT_SHIPPED_DTTM, BULK_TRACK_DELIVERY_DTTM) AS STD
    FROM EDLDB.CHEWYBI.SHIPMENT_TRANSACTIONS
    WHERE ORDER_ID IN (
        SELECT ORDER_ID
        FROM EDLDB.CHEWYBI.ORDERS
        WHERE CUSTOMER_ID = :customer_id
        AND ORDER_PLACED_DTTM >= CURRENT_DATE - 90
        GROUP BY ORDER_ID
    )
    AND BULK_TRACK_LB_PACKAGE_WEIGHT IS NOT NULL
    AND ORDER_PLACED_DTTM IS NOT NULL
    AND BULK_TRACK_DELIVERY_DTTM IS NOT NULL
    GROUP BY ALL
) 
SELECT 
    POSTCODE, 
    SHIPMENT_SHIP_ROUTE,
    COUNT(DISTINCT SHIPMENT_TRACKING_NUMBER) AS SHIPMENT_COUNT,
    MIN(PACKAGE_WEIGHT) AS MIN_PACKAGE_WEIGHT,
    MAX(PACKAGE_WEIGHT) AS MAX_PACKAGE_WEIGHT,
    AVG(PACKAGE_WEIGHT) AS AVG_PACKAGE_WEIGHT,
    MEDIAN(PACKAGE_WEIGHT) AS MEDIAN_PACKAGE_WEIGHT,
    MIN(CTD) AS MIN_CTD,
    MAX(CTD) AS MAX_CTD,
    AVG(CTD) AS AVG_CTD,
    MEDIAN(CTD) AS MEDIAN_CTD,
    MIN(CTR) AS MIN_CTR,
    MAX(CTR) AS MAX_CTR,
    AVG(CTR) AS AVG_CTR,
    MEDIAN(CTR) AS MEDIAN_CTR,
    MIN(RTS) AS MIN_RTS,
    MAX(RTS) AS MAX_RTS,
    AVG(RTS) AS AVG_RTS,
    MEDIAN(RTS) AS MEDIAN_RTS,
    MIN(STD) AS MIN_STD,
    MAX(STD) AS MAX_STD,
    AVG(STD) AS AVG_STD,
    MEDIAN(STD) AS MEDIAN_STD,
    COUNT(CASE WHEN CTD > 3 THEN 1 END) AS DELAYED_SHIPMENTS,
    COUNT(CASE WHEN CTD > 3 THEN 1 END) / COUNT(*)::FLOAT * 100 AS DELAY_RATE_PCT
FROM BASE
GROUP BY ALL
ORDER BY POSTCODE, SHIPMENT_SHIP_ROUTE;
