-- Shipment Inspector Data Query (from tool_calls.py)
-- Retrieves enhanced shipment data from inspector table for validation

SELECT ACTUAL_SHIP_DATE, SHIPMENT_TRACKING_NUMBER, ORDER_ID, FFMCENTER_NAME, 
       FFMCENTER_POSTCODE, FFMCENTER_STATE, NETWORK_TYPE, CARRIER_CODE, 
       CUSTOMER_POSTCODE, CUSTOMER_STATE, SHIP_ROUTE, IS_MIDDLE_MILE, 
       CONTENT_TYPE, ARC_RANGE, IS_NEW_CUSTOMER, IS_AUTOSHIP, IS_BACKORDERED, 
       IS_MULTI_PACKAGE, IS_CONSOLIDATED_ORDER, ORDER_IS_SPLIT, ORDER_IS_SPLIT_LOW_COST, 
       ORDER_PLACED_DTTM, SHIPMENT_RELEASE_DTTM, SHIPMENT_SHIP_DTTM, SHIPMENT_DELIVERY_DTTM, 
       UPSTREAM_ORDER_PACKAGE_COUNT, ORS_ORDER_PACKAGE_COUNT, ORDER_TOTAL_PACKAGE_COUNT, 
       SHIPMENT_COST, ORDER_CNT_PER_PACKAGE, CONSOLIDATED_SHIPMENT_COST, ESTIMATED_SHIP_COST, 
       CONSOLIDATED_ESTIMATED_SHIP_COST, UNITS_SHIPPED, PACKAGE_COUNT, INVOICED_PACKAGE_COUNT, 
       ESTIMATED_OR_INVOICED_PACKAGE_COUNT, ZONE_INVOICED, ZONE_EXPECTED, WEIGHT_INVOICED, 
       WEIGHT_EXPECTED, VOLUME_EXPECTED, TNT_EXPECTED, ARC_DISTANCE, BEST_FC_ARC_DISTANCE, 
       ORDER_COUNT, INVOICED_ORDER_COUNT, ESTIMATED_OR_INVOICED_ORDER_COUNT, TOTAL_NET_SALES, 
       CTD/(24*60*60) AS CLICK_TO_DELIVER_DAYS, 
       CTR/(24*60*60) AS CLICK_TO_RELEASE_DAYS, 
       RTS/(24*60*60) AS RELEASE_TO_SHIP_DAYS, 
       STD/(24*60*60) AS SHIP_TO_DELIVER_DAYS
FROM edldb.sc_user_tools_analytics_sandbox.uta_shipment_inspector_sf
WHERE order_id IN (
    SELECT DISTINCT order_id 
    FROM edldb.chewybi.orders
    WHERE customer_id = :customer_id
    AND ORDER_PLACED_DTTM >= CURRENT_DATE - 90
)
ORDER BY ORDER_PLACED_DTTM DESC, SHIPMENT_TRACKING_NUMBER;
