-- =================================================================
-- CUSTOMER INFORMATION QUERY
-- =================================================================
-- Template: customer_information_query
-- Description: Comprehensive customer and pet profile data extraction
-- Source: cat_as_order_agency/as_sql_execution.py
-- Parameters: :customer_id
-- Usage: Extract customer demographics, autoship statistics, and pet profile details

SELECT
      C.CUSTOMER_ID
      ,C.CUSTOMER_REGISTRATION_DTTM
      ,C.CUSTOMER_LAST_SESSION_DTTM
      ,C.CUSTOMER_ORDER_FIRST_PLACED_DTTM
      ,C.CUSTOMER_ORDER_LAST_PLACED_DTTM
      ,C.CUSTOMER_ORDER_FIRST_AUTOREORDER_PLACED_DTTM
      ,C.CUSTOMER_PREFERRED_FOOD_BRANDS
      ,C.CUSTOMER_PETS
      ,C.LOYALTY_MEMBER_FLAG
      ,C.IS_VETCARE_CUSTOMER
      ,LISTAGG(P.PET_PROFILE_ID, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS PET_PROFILE_ID
      ,LISTAGG(P.PET_AGE, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS PET_AGE
      ,LISTAGG(P.PET_BREED, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS PET_BREED
      ,LISTAGG(P.PET_NAME, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS PET_NAME
      ,LISTAGG(P.BIRTHDAY, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS BIRTHDAY
      ,LISTAGG(P.PET_TYPE, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS PET_TYPE
      ,LISTAGG(P.ALLERGIES, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS ALLERGIES
      ,LISTAGG(P.GENDER, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS GENDER
      ,LISTAGG(P.HEALTH_CONDITIONS, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS HEALTH_CONDITIONS
      ,LISTAGG(P.WEIGHT, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS WEIGHT
      ,LISTAGG(P.LIFESTAGE, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS LIFESTAGE
      ,LISTAGG(P.LIFESTAGE_GROUP, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS LIFESTAGE_GROUP
      ,LISTAGG(P.MEDICATION, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS MEDICATION
      ,LISTAGG(P.VET_INFORMATION_ADDED_FLAG, ' | ') WITHIN GROUP (ORDER BY P.PET_PROFILE_ID) AS VET_INFORMATION_ADDED_FLAG
FROM EDLDB.CHEWYBI.CUSTOMERS C
LEFT JOIN EDLDB.CHEWYBI.PET_PROFILE_AGGREGATE P
       ON C.CUSTOMER_ID = P.CUSTOMER_ID
WHERE C.CUSTOMER_ID = :customer_id
AND PP_STATUS ILIKE 'Active'
GROUP BY ALL;
